# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Constantine Gochev
title: Software Engineer
email: constantingochev1993@gmail.com
website: https://constantinegochev.github.io/

# Social links
# twitter_username: facespics
github_username: constantinegochev
stackoverflow_username: 7207993/c-gochev?tab=profile
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: константин-гочев-97a224151
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/snimka.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Constantine and I'm a backend software engineer.

  I have 4 years of experience in the industry gaining teamwork and leadership skills.

  I am most skilled in <mark>Javascript</mark> using the language both as a backend with <mark>Node.js</mark> and UI(react.js).
  Databases of choice for me are: <mark> MongoDB </mark>,<mark> Redis </mark> or <mark> Postgresql</mark> depending on the needs of the project.
  As well as engineering systems I also have experience administrating <mark>Linux</mark> systems
  and virtualizing services with  <mark> Docker</mark> and <mark>KVM</mark>.
  I also have a deep interest in low level programming with languages such as <mark>C</mark> and <mark>Rust</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Running
   - Reading

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
