# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Constantine Gochev
title: Software Engineer
email: constantinegochev1993@gmail.com
website: https://constantinegochev.github.io/

# Social links
# twitter_username: facespics
github_username:  constantinegochev
stackoverflow_username: C.Gochev
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: константин-гочев
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Constantine and I'm a software engineer. As well as engineering systems I also have experience administrating linux systems. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Javascript</mark> and <mark>MongoDB</mark>

  Very into <mark>Rust</mark> lately incorporating it into my services.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Sailing
   - Snooker
   - Running

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
