# Content configuration version
version: 1
# Site
repository: "sproogen/resume-theme"
favicon: images/favicon.ico

# Personal info
name: Constantine Gochev
title: Software Engineer
email: cg@cryptobooking.world
website: https://constantinegochev.github.io/

# Social links
# twitter_username: facespics
github_username: constantinegochev
stackoverflow_username: 7207993/c-gochev
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: константин-гочев-97a224151
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Introducion
about_profile_image: images/photo2.png
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Constantine and I enjoy writing code.
  I have the most experience with <mark>Javascript</mark>, using the language both as a backend and user interface.
  Databases I have used in production are: <mark> Postgresql</mark>, <mark> MongoDB </mark>,<mark> Redis </mark> depending on the needs of the project.
  I prefer to use <mark>Linux</mark> systems for my servers, also have used <mark> Docker</mark> quite a bit.
  I have had interest in lower level programming with languages such as <mark>Go</mark> <mark>C</mark> and <mark>Rust</mark>
  and would like to further my knowledge there.

# More Section
more_title: About Me
more_content: | # this will include new lines to allow paragraphs
  I have a great family and my biggest goal is to find a way to make the world a place in the future where people
  will have sovereignty over their minds, bodies and finances. 
  The massive priority for me in the coming years is to support freedom of speech and freedom of movement and assembly :)
  My other interests include studying history, playing snooker and pool, doing some sailing,
  yoga and martial arts.

# Footer
footer_show_references: true
github: [metadata]
# Build settings
remote_theme: "sproogen/resume-theme"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
